language: go
go:
- 1.5.4
- 1.6.2
env:
  global:
    - GO15VENDOREXPERIMENT=1
install:
- go get github.com/nats-io/nats
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
script:
- go build
- go fmt ./...
- go vet ./...
- go test -i -race ./...
- go test -v -race ./...
after_script:
- if [ "$TRAVIS_GO_VERSION" = "1.6.2" ]; then ./scripts/cov.sh TRAVIS; fi
- if [ "$TRAVIS_GO_VERSION" = "1.6.2" ] && [ "$TRAVIS_TAG" != "" ]; then ./scripts/cross_compile.sh $TRAVIS_TAG; ghr --username nats-io --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi
